### PR TITLE
ANNPLT-116: Added missing TinyMCE stylesheets

### PR DESCRIPTION
**Pull request by jonathanmtran**
https://issues.jasig.org/browse/ANNPLT-116

### CODE REVIEW

**Comment by jonathanmtran** [comment]
> One small request, could the WYSIWYG be configured to be persistent instead of only on focus?

Sure @ChristianMurphy! It seems that TinyMCE v4.x's default is the [inline editor](https://www.tinymce.com/docs/get-started/use-tinymce-inline/). I can quickly put that together since we have it implemented at our institution.

screenshot from 2016-12-15 at 09 51 13

**Comment by ChristianMurphy** [comment]
> I can quickly put that together since we have it implemented at our institution.

@jonathanmtran Do you have the availability to do this soon?
If not I could set aside some time put together a PR with the changes to help this move forward.

**Comment by jonathanmtran** [comment]
Apologies for the delayed response @ChristianMurphy. Looks like you beat me to the punch.

**Comment by ChristianMurphy** [comment]
No worries.
I cherry-picked this PR code's which gave a good starting point. :+1: :bowing_man: 
If you have a chance feedback would be appreciated on #44 .

**Comment by jonathanmtran** [comment]
Merged as a part of #44

**Pull request closed without merging**
