### PR TITLE
Removed guest based caching

### PR DESCRIPTION
**Pull request by bpowell**
Guests are treated as normal users

@drewwills

### CODE REVIEW

**Comment by drewwills** [comment]
Looks good! :+1: It's an improvement that announcements for guest users have the same caching behavior as authenticated users.

But it begs the question... _should announcements be cached for all users?_

**Comment by bpowell** [comment]
@drewwills I think it should be cached for everyone, but I'd like to do that using annotations like `@Cacheable` and not doing it the way it was done for guests. Doing it that way would take a bit longer to the point that I think this should be merged and we can work on the caching after the new year.

**Comment by bpowell** [comment]
@drewwills did you get a chance to review what I said before the break?

**Comment by drewwills** [comment]
@bpowell -- I saw your post before the break and agreed with it (still do).  We should go ahead and merge this change.

**Pull request merged**
