### PR TITLE
chore(deps): update dependency commons-collections:commons-collections to v20040616

### PR DESCRIPTION
**Pull request by ChristianMurphy**
This PR contains the following updates:

| Package | Update | Change | References |
|---|---|---|---|
| commons-collections:commons-collections | major | `3.2.2` -> `20040616` | [homepage](http://www.ja-sig.org/wiki/display/PLT/Announcements+Portlet) |

---

### Renovate configuration

:date: **Schedule**: At any time (no schedule defined).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Whenever PR is stale, or if you modify the PR title to begin with "`rebase!`".

:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://renovatebot.com).

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
This seems to be reverting to a previous version?
Maybe the date is being interpreted as the major version?
Commons collection 4 upgrade worked as expected. https://github.com/Jasig/email-preview/pull/91

/cc @rarkins not sure if this is a fluke or a bug, will keep an eye out to see if it happens again.

**Comment by ChristianMurphy** [comment]
### Renovate Ignore Notification

As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for *any* future 20040616.x releases. However, if you upgrade to 20040616.x manually then Renovate will then reenable updates for minor and patch updates automatically.

If this PR was closed by mistake or you changed your mind, you can simply rename this PR and you will soon get a fresh replacement PR opened.

**Comment by rarkins** [comment]
It’s a higher (numerically) version. Is there some standard for how a computer could tell that a library switched from calendar versioning to semver?

**Comment by ChristianMurphy** [comment]
> standard for how a computer could tell that a library switched from calendar versioning to semver

There is not, very little about maven versioning is standard.
Is there a way to tell renovate to use semver only or date base only versions for a specific package?

**Comment by rarkins** [comment]
You actually can normally control the version scheme down to individual packages but it's not supported yet for Gradle due to the way we use a plugin to skip the usual lookup logic.

**Pull request closed without merging**
